// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddtuomkjljhiscabjgmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdHVvbWtqbGpoaXNjYWJqZ214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODM0NjksImV4cCI6MjA1ODc1OTQ2OX0.FILjnODvkTAKKblZmgbnyZ6Ag7dlqz_RItTCcL-ou4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);